import { Match, Player, SubCandidate, TeamSettings } from "@/types/footy";

export const initialTeamSettings: TeamSettings = {
  name: "Bushwick Borough FC",
  leagueName: "NYC Footy - Fall 2026",
  division: "P3 Co-ed Sunday Division",
  format: "7v7",
  targetSquadSize: 8, // 7 starters + 1-2 subs for rotation
  minFemalePlayers: 2, // Official NYC Footy co-ed rule
  homeKitColor: "White (Light)",
  awayKitColor: "Navy Blue (Dark)",
  captainName: "Ethan Quigley",
  captainPhone: "917-555-0142",
};

export const initialPlayers: Player[] = [
  {
    id: "p1",
    name: "Ethan Quigley",
    number: 7,
    gender: "male",
    preferredPositions: ["DEF", "MID"],
    isCaptain: true,
    phone: "917-555-0142",
  },
  {
    id: "p2",
    name: "Mariama Bah",
    number: 10,
    gender: "female",
    preferredPositions: ["MID", "FWD"],
    phone: "646-555-0188",
  },
  {
    id: "p3",
    name: "Eris Gao",
    number: 3,
    gender: "female",
    preferredPositions: ["DEF", "MID"],
    phone: "212-555-0121",
  },
  {
    id: "p4",
    name: "Will Quigley",
    number: 4,
    gender: "male",
    preferredPositions: ["DEF"],
    phone: "917-555-0119",
  },
  {
    id: "p5",
    name: "Brady Miller",
    number: 8,
    gender: "male",
    preferredPositions: ["MID"],
    phone: "347-555-0193",
  },
  {
    id: "p6",
    name: "Rohit Subramaniam",
    number: 11,
    gender: "male",
    preferredPositions: ["MID", "FWD"],
    phone: "917-555-0162",
  },
  {
    id: "p7",
    name: "Sahil Doshi",
    number: 9,
    gender: "male",
    preferredPositions: ["FWD"],
    phone: "212-555-0134",
  },
  {
    id: "p8",
    name: "Chris Tellez Luna",
    number: 5,
    gender: "male",
    preferredPositions: ["DEF"],
    phone: "929-555-0177",
  },
  {
    id: "p9",
    name: "Rahul Fernandez",
    number: 6,
    gender: "male",
    preferredPositions: ["MID"],
    phone: "347-555-0148",
  },
  {
    id: "p10",
    name: "Ahmed Tariq",
    number: 1,
    gender: "male",
    preferredPositions: ["GK"],
    phone: "646-555-0155",
  },
  {
    id: "p11",
    name: "Aravind Elangovan",
    number: 14,
    gender: "male",
    preferredPositions: ["FWD", "MID"],
    phone: "917-555-0190",
  },
  {
    id: "p12",
    name: "Neil Maru",
    number: 12,
    gender: "male",
    preferredPositions: ["MID"],
    phone: "646-555-0172",
  },
];

export const initialSubCandidates: SubCandidate[] = [
  {
    id: "sub-1",
    name: "Emma Rodriguez",
    phone: "347-555-0128",
    gender: "female",
    positions: ["MID", "FWD"],
    tier: 1,
    reliabilityScore: 5,
    statusForNextMatch: "uncontacted",
    notes: "Super reliable, played college ball. Always down for Sunday games.",
    lastPlayedDate: "2026-09-08",
  },
  {
    id: "sub-2",
    name: "Dave 'The Wall' Kowalski",
    phone: "646-555-0199",
    gender: "male",
    positions: ["GK"],
    tier: 1,
    reliabilityScore: 5,
    statusForNextMatch: "uncontacted",
    notes: "Elite goalkeeper. Great communication from the back.",
    lastPlayedDate: "2026-09-15",
  },
  {
    id: "sub-3",
    name: "Olivia Taylor",
    phone: "212-555-0177",
    gender: "female",
    positions: ["DEF", "MID"],
    tier: 1,
    reliabilityScore: 5,
    statusForNextMatch: "uncontacted",
    notes: "Solid center-back, never commits fouls, great passing.",
    lastPlayedDate: "2026-08-30",
  },
  {
    id: "sub-4",
    name: "Alex Chen",
    phone: "917-555-0183",
    gender: "male",
    positions: ["DEF", "MID"],
    tier: 2,
    reliabilityScore: 4,
    statusForNextMatch: "uncontacted",
    notes: "Ethan's coworker. Fast winger, needs 2 days advance notice.",
    lastPlayedDate: "2026-08-16",
  },
  {
    id: "sub-5",
    name: "Sam Miller",
    phone: "929-555-0112",
    gender: "male",
    positions: ["FWD"],
    tier: 3,
    reliabilityScore: 3,
    statusForNextMatch: "uncontacted",
    notes: "Decent striker, but sometimes responds late.",
    lastPlayedDate: "2026-07-20",
  },
  {
    id: "sub-6",
    name: "Jessica Wu",
    phone: "646-555-0210",
    gender: "female",
    positions: ["MID"],
    tier: 2,
    reliabilityScore: 4,
    statusForNextMatch: "uncontacted",
    notes: "Lives near Bushwick Inlet. Can bike over quickly if needed.",
    lastPlayedDate: "2026-09-01",
  },
];

export const initialMatches: Match[] = [
  {
    id: "match-4",
    week: 4,
    opponent: "Greenpoint Athletic",
    date: "2026-09-27",
    time: "16:00",
    location: "Bushwick Inlet Park (Williamsburg)",
    fieldNumber: "Field 1 (Turf)",
    googleMapsUrl: "https://maps.google.com/?q=Bushwick+Inlet+Park+Brooklyn",
    subwayInfo: "L Train to Bedford Ave or G Train to Nassau Ave",
    kitColor: "Light",
    pollDeadline: "2026-09-25T17:00:00",
    requiredPlayers: 8, // 7 starters + 1 sub
    requiredFemalePlayers: 2,
    rsvps: {
      p1: { status: "yes", updatedAt: "2026-09-22T10:00:00" }, // Ethan Quigley
      p2: { status: "yes", updatedAt: "2026-09-22T10:05:00" }, // Mariama Bah
      p3: { status: "no", reason: "Attending friend's wedding upstate", updatedAt: "2026-09-22T10:30:00" }, // Eris Gao
      p4: { status: "pending", updatedAt: "2026-09-22T09:00:00" }, // Will Quigley
      p5: { status: "maybe", reason: "Might have work overtime Sunday afternoon", updatedAt: "2026-09-22T11:15:00" }, // Brady Miller
      p6: { status: "yes", updatedAt: "2026-09-22T10:12:00" }, // Rohit Subramaniam
      p7: { status: "yes", updatedAt: "2026-09-22T10:45:00" }, // Sahil Doshi
      p8: { status: "yes", updatedAt: "2026-09-22T11:00:00" }, // Chris Tellez Luna
      p9: { status: "no", reason: "Hamstring soreness, resting this week", updatedAt: "2026-09-22T11:20:00" }, // Rahul Fernandez
      p10: { status: "yes", updatedAt: "2026-09-22T11:30:00" }, // Ahmed Tariq (GK)
      p11: { status: "yes", updatedAt: "2026-09-22T11:40:00" }, // Aravind Elangovan
      p12: { status: "maybe", reason: "Traveling back Sunday morning", updatedAt: "2026-09-22T11:50:00" }, // Neil Maru
    },
    subsConfirmed: [],
    notes: "Crucial match for playoff seeding! Need to bring the 2 team match balls and ice pack.",
  },
  {
    id: "match-5",
    week: 5,
    opponent: "Pier 40 Pumas",
    date: "2026-10-04",
    time: "15:00",
    location: "Pier 40 (Hudson River Park)",
    fieldNumber: "Courtyard Field (West)",
    googleMapsUrl: "https://maps.google.com/?q=Pier+40+Hudson+River+Park",
    subwayInfo: "1 Train to Houston St or PATH to Christopher St",
    kitColor: "Dark",
    pollDeadline: "2026-10-02T17:00:00",
    requiredPlayers: 8,
    requiredFemalePlayers: 2,
    rsvps: {
      p1: { status: "yes", updatedAt: "2026-09-22T10:00:00" },
      p2: { status: "yes", updatedAt: "2026-09-22T10:00:00" },
    },
    subsConfirmed: [],
    notes: "Watch out for their number 9, high press team.",
  },
  {
    id: "match-6",
    week: 6,
    opponent: "Cobble Hill Kickers",
    date: "2026-10-11",
    time: "17:30",
    location: "Brooklyn Bridge Park Pier 5",
    fieldNumber: "Field 2",
    googleMapsUrl: "https://maps.google.com/?q=Brooklyn+Bridge+Park+Pier+5",
    subwayInfo: "A/C to High St, 2/3 to Clark St, or NYC Ferry to DUMBO/BBP",
    kitColor: "Light",
    pollDeadline: "2026-10-09T17:00:00",
    requiredPlayers: 8,
    requiredFemalePlayers: 2,
    rsvps: {},
    subsConfirmed: [],
  },
  {
    id: "match-3",
    week: 3,
    opponent: "DUMBO United",
    date: "2026-09-20",
    time: "16:00",
    location: "Bushwick Inlet Park (Williamsburg)",
    fieldNumber: "Field 1",
    googleMapsUrl: "https://maps.google.com/?q=Bushwick+Inlet+Park+Brooklyn",
    kitColor: "Light",
    pollDeadline: "2026-09-18T17:00:00",
    requiredPlayers: 8,
    requiredFemalePlayers: 2,
    rsvps: {
      p1: { status: "yes", updatedAt: "2026-09-18T10:00:00" },
      p2: { status: "yes", updatedAt: "2026-09-18T10:00:00" },
      p3: { status: "yes", updatedAt: "2026-09-18T10:00:00" },
      p5: { status: "yes", updatedAt: "2026-09-18T10:00:00" },
      p7: { status: "yes", updatedAt: "2026-09-18T10:00:00" },
      p8: { status: "yes", updatedAt: "2026-09-18T10:00:00" },
      p9: { status: "yes", updatedAt: "2026-09-18T10:00:00" },
    },
    subsConfirmed: ["sub-1"],
    score: { us: 3, opponent: 2 },
    notes: "Great comeback win! Issac scored a brace and Emma (sub) sealed it with a header.",
  },
  {
    id: "match-2",
    week: 2,
    opponent: "Williamsburg Wolves",
    date: "2026-09-13",
    time: "14:30",
    location: "Randall's Island",
    fieldNumber: "Field 70",
    googleMapsUrl: "https://maps.google.com/?q=Randalls+Island+Field+70",
    kitColor: "Dark",
    pollDeadline: "2026-09-11T17:00:00",
    requiredPlayers: 8,
    requiredFemalePlayers: 2,
    rsvps: {},
    subsConfirmed: [],
    score: { us: 1, opponent: 1 },
    notes: "Rainy game, slippery turf. Solid defense by Ethan and Marcus.",
  },
  {
    id: "match-1",
    week: 1,
    opponent: "SoHo Strikers",
    date: "2026-09-06",
    time: "18:00",
    location: "Octagon Park (Roosevelt Island)",
    fieldNumber: "Main Turf",
    googleMapsUrl: "https://maps.google.com/?q=Octagon+Park+Roosevelt+Island",
    kitColor: "Light",
    pollDeadline: "2026-09-04T17:00:00",
    requiredPlayers: 8,
    requiredFemalePlayers: 2,
    rsvps: {},
    subsConfirmed: [],
    score: { us: 2, opponent: 0 },
    notes: "Clean sheet on season opener! Halley dominated midfield.",
  },
];
